### ISSUE TITLE
Replace Trever

### ISSUE THREAD

**Issue by MichaelStatt-S** [FRC5892/HeroHours#35]
I don't really like being so dependent on Traver (#13). I think it should only be used for special one-off things that its not worth automating. It shouldn't be too hard to implement what we are doing currently with Trevor

**Comment by yyy2356** [comment]
as far as i can tell, the teachers and mentors really like trevor. Why shouldnt we use it?

**Comment by yyy2356** [comment]
for other people to copy it, its as simple as exporting the queries and adding them as files. Trevor is a pretty simple system to use. The reason the mentors like Trevor is because its accessible anywhere and it looks good. adding extra functionality is good for sheets, though not fully necessary, but in terms of the dashboard, Trevor does a really solid job. We should discuss at todays meeting and get another opinion.

**Comment by MichaelStatt-S** [comment]
I'm not saying we need to remove trevor all together, but I would consider the sheets a requirement/ core functionality. All I've done in the pr is make an endpoint for the data, instead of relying on trevor. Trevor is still good for a ui used for occasional queries. I just don't like using it for the 'live user list', 'live activity logs', and each meeting

**Comment by yyy2356** [comment]
the primary reason that i like trevor is that it automatically refreshes the data on the sheet hourly. I dont know if thats a unique behavior of trevor, or something built into sheets. if its the former, i would definitely want to keep trevor, if its the latter, im all for switching it out from the sheets and only using it for dashboards

**Comment by MichaelStatt-S** [comment]
That hourly refresh is built into Google sheets. It just uses a built in formula that downloads a csv of the data. I implemented that in the pr (custom formula for not absolutely garbage auth)
